### ISSUE TITLE
Network errors: Unable to load various fonts with 404

### ISSUE THREAD

**Issue by brew** [okfn/services#4]
The browser console shows several fonts in the lato family are not loading with a 404 Not Found eror: e.g. http://services.okfn.org/css/font/lato-regular.woff

**Comment by smth** [comment]
Interesting.. I can't replicate this. This is happening on the live site for you @brew ?

**Comment by brew** [comment]
Yeah, this is on the live site. Perhaps you're seeing local fonts? The link to the font example above is a 404. 

The sass files points to `font/lato-regular.woff` as there is a `font` directory in the `_sass` directory, so that sort of makes sense. But there's no equivalent path to a `font` directory or lato font files in the css directory.

I've got a fix that copies the lato font files to the existing `css/fonts` directory, and overrides the sass variable `$lato-font-path` to point to it.

**Comment by brew** [comment]
Fixed in cb929de19300b12abfdeafa1c8f1356db9e38d08.

**Comment by smth** [comment]
I tried disabling the font locally, in case that was why, but everything still appeared to be fine. I would have expected to see the the console errors either way. Weird. That looks like a good fix though, thanks.
